import { DataTypes, Sequelize } from 'sequelize';

export default (sequelize: Sequelize) => {
  return sequelize.define(
    'khats',
    {
      id: { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true },
      zone_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      mehfil_directory_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      email: { type: DataTypes.STRING(255), allowNull: true },
      phone_number: { type: DataTypes.STRING(255), allowNull: false },
      full_name: { type: DataTypes.STRING(255), allowNull: false },
      father_name: { type: DataTypes.STRING(255), allowNull: false },
      introducer_name: { type: DataTypes.STRING(255), allowNull: true },
      age: { type: DataTypes.INTEGER, allowNull: false },
      ehad_duration: { type: DataTypes.STRING(255), allowNull: false },
      address: { type: DataTypes.TEXT, allowNull: true },
      city: { type: DataTypes.STRING(255), allowNull: true },
      last_tarteeb: { type: DataTypes.STRING(255), allowNull: true },
      consistent_in_wazaif: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      consistent_in_prayers: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      consistent_in_ishraq: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      makes_up_missed_prayers: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      missed_prayers: { type: DataTypes.TEXT, allowNull: true },
      can_read_quran: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      multan_visit_frequency: { type: DataTypes.STRING(255), allowNull: false },
      mehfil_attendance_frequency: { type: DataTypes.STRING(255), allowNull: false },
      is_submitted_before: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
      last_submission_wazaifs: { type: DataTypes.TEXT, allowNull: true },
      kalimah_quantity: { type: DataTypes.INTEGER, allowNull: false },
      allah_quantity: { type: DataTypes.INTEGER, allowNull: false },
      laa_ilaaha_illallah_quantity: { type: DataTypes.INTEGER, allowNull: false },
      sallallahu_alayhi_wasallam_quantity: { type: DataTypes.INTEGER, allowNull: false },
      astagfirullah_quantity: { type: DataTypes.INTEGER, allowNull: false },
      ayat_ul_kursi_quantity: { type: DataTypes.INTEGER, allowNull: false },
      dua_e_talluq_quantity: { type: DataTypes.INTEGER, allowNull: false },
      dua_e_waswasey_quantity: { type: DataTypes.INTEGER, allowNull: false },
      additional_wazaif_reading: { type: DataTypes.TEXT, allowNull: true },
      description: { type: DataTypes.TEXT, allowNull: true },
      reciter_relation: { type: DataTypes.STRING(255), allowNull: true },
      reciter_name: { type: DataTypes.STRING(255), allowNull: true },
      reciter_age: { type: DataTypes.INTEGER, allowNull: true },
      reciter_ehad_duration: { type: DataTypes.STRING(255), allowNull: true },
      reciter_consistent_in_wazaif: { type: DataTypes.BOOLEAN, allowNull: true },
      reciter_consistent_in_prayers: { type: DataTypes.BOOLEAN, allowNull: true },
      reciter_makes_up_missed_prayers: { type: DataTypes.BOOLEAN, allowNull: true },
      reciter_missed_prayers: { type: DataTypes.TEXT, allowNull: true },
      reciter_can_read_quran: { type: DataTypes.BOOLEAN, allowNull: true },
      reciter_multan_visit_frequency: { type: DataTypes.STRING(255), allowNull: true },
      reciter_mehfil_attendance_frequency: { type: DataTypes.STRING(255), allowNull: true },
      type: { type: DataTypes.ENUM('khat', 'masail'), allowNull: false, defaultValue: 'khat' },
      status: {
        type: DataTypes.ENUM('pending', 'in-review', 'awaiting-response', 'closed'),
        allowNull: false,
        defaultValue: 'pending',
      },
      jawab: { type: DataTypes.TEXT, allowNull: true },
      jawab_links: { type: DataTypes.TEXT, allowNull: true },
      notes: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      updated_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    },
    { tableName: 'khats', underscored: true, timestamps: true },
  );
};
