import { DataTypes, Sequelize } from 'sequelize';

export default (sequelize: Sequelize) => {
  return sequelize.define(
    'tarteeb_requests',
    {
      id: { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true },
      zone_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      mehfil_directory_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      email: { type: DataTypes.STRING(255), allowNull: false },
      phone_number: { type: DataTypes.STRING(255), allowNull: false },
      full_name: { type: DataTypes.STRING(255), allowNull: false },
      father_name: { type: DataTypes.STRING(255), allowNull: false },
      age: { type: DataTypes.INTEGER, allowNull: false },
      gender: { type: DataTypes.ENUM('male', 'female'), allowNull: false },
      city: { type: DataTypes.STRING(255), allowNull: false },
      country: { type: DataTypes.STRING(255), allowNull: false },
      introducer_name: { type: DataTypes.STRING(255), allowNull: false },
      ehad_duration: { type: DataTypes.STRING(255), allowNull: false },
      source_of_income: { type: DataTypes.STRING(255), allowNull: false },
      education: { type: DataTypes.STRING(255), allowNull: false },
      marital_status: {
        type: DataTypes.ENUM('single', 'married', 'divorced', 'widowed'),
        allowNull: false,
      },
      consistent_in_wazaif: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      consistent_in_prayers: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      missed_prayers: { type: DataTypes.TEXT, allowNull: true },
      makes_up_missed_prayers: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      nawafil: { type: DataTypes.INTEGER, allowNull: true },
      can_read_quran: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      consistent_in_ishraq: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      consistent_in_tahajjud: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      amount_of_durood: { type: DataTypes.INTEGER, allowNull: false },
      listens_taleem_daily: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      last_wazaif_tarteeb: { type: DataTypes.STRING(255), allowNull: true },
      multan_visit_frequency: { type: DataTypes.STRING(255), allowNull: true },
      mehfil_attendance_frequency: { type: DataTypes.STRING(255), allowNull: true },
      household_members_in_ehad: { type: DataTypes.INTEGER, allowNull: true },
      reads_current_wazaif_with_ease: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      able_to_read_additional_wazaif: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      wazaif_consistency_duration: { type: DataTypes.STRING(255), allowNull: true },
      does_dum_taweez: { type: DataTypes.TINYINT, allowNull: false, defaultValue: 0 },
      kalimah_quantity: { type: DataTypes.INTEGER, allowNull: true },
      allah_quantity: { type: DataTypes.INTEGER, allowNull: true },
      laa_ilaaha_illallah_quantity: { type: DataTypes.INTEGER, allowNull: true },
      sallallahu_alayhi_wasallam_quantity: { type: DataTypes.INTEGER, allowNull: true },
      astagfirullah_quantity: { type: DataTypes.INTEGER, allowNull: true },
      ayat_ul_kursi_quantity: { type: DataTypes.INTEGER, allowNull: true },
      dua_e_talluq_quantity: { type: DataTypes.INTEGER, allowNull: true },
      subhanallah_quantity: { type: DataTypes.INTEGER, allowNull: true },
      dua_e_waswasey_quantity: { type: DataTypes.INTEGER, allowNull: true },
      other_wazaif: { type: DataTypes.TEXT, allowNull: true },
      wazaif_not_reading: { type: DataTypes.TEXT, allowNull: true },
      additional_wazaif_reading: { type: DataTypes.TEXT, allowNull: true },
      issues_facing: { type: DataTypes.TEXT, allowNull: true },
      status: { type: DataTypes.STRING(255), allowNull: false, defaultValue: 'pending' },
      jawab: { type: DataTypes.TEXT, allowNull: true },
      jawab_links: { type: DataTypes.TEXT, allowNull: true },
      notes: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      updated_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
      created_at: { type: DataTypes.DATE, allowNull: true },
      updated_at: { type: DataTypes.DATE, allowNull: true },
    },
    { tableName: 'tarteeb_requests', timestamps: false, underscored: true },
  );
};
