import { Router } from 'express';
import { route } from '../../Enums/routeEnums';

import taleemRoutes from './taleem.route';
import naatRoutes from './naat.route';
import messagesRoutes from './messages.route';
import mehfilsRoutes from './mehfils.route';
import wazaifsRoutes from './wazaifs.route';
import searchRoutes from './search.route';
import categoriesRoutes from './categories.route';
import tagsRoutes from './tags.route';
import authRoutes from './auth.route';
import parhaiyanRoutes from './parhaiyan.route';
import parhaiyanRecitaionsRoutes from './parhaiyan-recitations.route';
import zoneRoutes from './zones.route';
import regionRoutes from './regions.route';
import mehfilDirectoryRoutes from './mehfil-directories.route';
import namazRoutes from './namaz.route';
import ehadKarkunRoutes from './ehadKarkun.route';
import karkunRoutes from './karkun.route';
import permissionRoutes from './permissions.route';
import rolesRoutes from './roles.route';
import adminUsersRoutes from './admin-users.route';
import feedbackRoutes from './feedback.route';
import karkunJoinRequestsRoute from './karkunJoinRequests.route';
import mehfilReportsRoute from './mehfil-reports.route';
import tabarukatRoute from './tabarukat.route';
import newKarkunRoute from './newKarkun.route';
import newEhadFollowUpRoute from './newEhadFollowUp.route';
import mehfilCoordinatorRoute from './mehfilCoordinator.route';
import dutyTypeRoute from './dutyType.route';
import dutyRosterRoute from './dutyRoster.route';
import dashboardRoute from './dashboard.route';
import tarteebRequestsRoute from './tarteebRequests.route';
import khatRoute from './khat.route';
import responseTemplatesRoute from './responseTemplates.route';
import messageSchedulesRoute from './messageSchedules.route';
import fileUploadRoute from './fileUpload.route';
import committeesRoute from './committees.route';

const router = Router();

router.use(route.TALEEMAT, taleemRoutes);
router.use(route.NAATSHAREEFS, naatRoutes);
router.use(route.MESSAGES, messagesRoutes);
router.use(route.MEHFILSSHAREEFS, mehfilsRoutes);
router.use(route.WAZAIFS, wazaifsRoutes);
router.use(route.SEARCH, searchRoutes);
router.use(route.CATEGORIES, categoriesRoutes);
router.use(route.TAGS, tagsRoutes);
router.use(route.AUTH, authRoutes);
router.use(route.PARHAIYAN, parhaiyanRoutes);
router.use(route.PARHAIYAN_RECITAION, parhaiyanRecitaionsRoutes);
router.use(route.ZONE, zoneRoutes);
router.use(route.REGION, regionRoutes);
router.use(route.MEHFIL_DIRECTORY, mehfilDirectoryRoutes);
router.use(route.NAMAZ, namazRoutes);
router.use(route.EHAD_KARKUN, ehadKarkunRoutes);
router.use(route.KARKUN, karkunRoutes);
router.use(route.PERMISSIONS, permissionRoutes);
router.use(route.ROLE, rolesRoutes);
router.use(route.ADMIN_USERS, adminUsersRoutes);
router.use(route.FEEDBACK, feedbackRoutes);
router.use(route.KARKUN_JOIN_REQUEST, karkunJoinRequestsRoute);
router.use(route.MEHFIL_REPORTS, mehfilReportsRoute);
router.use(route.NEW_KARKUN, newKarkunRoute);
router.use(route.Tabarukat, tabarukatRoute);
router.use(route.NEW_EHAD_FOLLOW_UP, newEhadFollowUpRoute);
router.use(route.MEHFIL_COORDINATOR, mehfilCoordinatorRoute);
router.use(route.DUTY_TYPE, dutyTypeRoute);
router.use(route.DUTY_ROSTER, dutyRosterRoute);
router.use(route.DASHBOARD, dashboardRoute);
router.use(route.TARTEEB_REQUESTS, tarteebRequestsRoute);
router.use(route.KHAT, khatRoute);
router.use(route.RESPONSE_TEMPLATES, responseTemplatesRoute);
router.use(route.MESSAGE_SCHEDULES, messageSchedulesRoute);
router.use(route.FILE_UPLOAD, fileUploadRoute);
router.use(route.COMMITTEES, committeesRoute);

router.get('/healthcheck', (_req, res) => {
  res.status(200).json({ status: 'OK' });
});

export default router;
